apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: top
    app.kubernetes.io/managed-by: argocd
    project: top
    tier: cache
    monitoring: enabled
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: top
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 21.2.0
    helm:
      releaseName: redis
      valuesObject:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack # matches kube-prometheus-stack release label
  destination:
    namespace: mig
    name: "in-cluster"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true