apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: top
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 72.9.1
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        grafana:
          plugins:
            - grafana-exploretraces-app
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki-gateway.monitoring.svc.cluster.local
              access: proxy
              # Even with auth_enabled: false, Loki requires an org ID header
              # This is a known quirk - the value can be anything since auth is disabled
              jsonData:
                httpHeaderName1: "X-Scope-OrgID"
              secureJsonData:
                httpHeaderValue1: "fake"
            - name: Tempo
              type: tempo
              access: proxy
              url: http://tempo.monitoring.svc.cluster.local:3100
              uid: tempo
              jsonData:
                httpMethod: GET
                serviceMap:
                  datasourceUid: prometheus
                tracesToMetrics:
                  datasourceUid: prometheus
  destination:
    namespace: monitoring
    name: "in-cluster"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true