apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: top
  namespace: argocd
spec:
  description: Top project for ArgoCD
  sourceRepos:
    - https://github.com/vivektopiya-VALTECH/aoa-test.git
    - https://kubernetes.github.io/ingress-nginx
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://charts.bitnami.com/bitnami
    - https://provectus.github.io/kafka-ui-charts
    - https://charts.external-secrets.io
    - https://helm.releases.hashicorp.com
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: networking.k8s.io
      kind: IngressClass
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: external-secrets.io
      kind: ClusterSecretStore